name: "snyk code test per cx but aiming to fail with linux"
## works with actions/checkout@v3 and snyk/actions/node@master
## works with actions/checkout@v2 and snyk/actions/node@master

on: [push, pull_request]
jobs:
  sast:
    name: Snyk Code Scan TEST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 
       # uses: actions/checkout@v2 
        with: 
          fetch-depth: 0
        
      - name: Run snyk to check for vulns TEST
     #   uses: snyk/actions/node@master
        uses: snyk/actions/setup@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test


## from existing one, which fails:

#build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: snyk/actions/setup@master
#      - name: Snyk Test
#        run: snyk code test --org=${{ secrets.SNYK_ORG }} --sarif > snyk-sarif2.json
#        continue-on-error: true
#        env:
#           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#      - name: Upload SARIF file
#        uses: github/codeql-action/upload-sarif@v1
#        with:
#          sarif_file: snyk-sarif2.json
